/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    ['W-WINDOW-10.6x2.4x0.25m.001_1']: THREE.Mesh
    ['W-WINDOW-10.6x2.4x0.25m.001_2']: THREE.Mesh
  }
  materials: {
    ['FrontColor.009']: THREE.MeshStandardMaterial
    ['BackColor.017']: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/Skylark/W-WINDOW-06x24x025m.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="W-WINDOW-106x24x025m001"
          rotation={[Math.PI / 2, 0, 0]}
          userData={{ name: 'W-WINDOW-10.6x2.4x0.25m.001' }}>
          <mesh
            name="W-WINDOW-10.6x2.4x0.25m.001_1"
            material={materials['FrontColor.009']}
            geometry={nodes['W-WINDOW-10.6x2.4x0.25m.001_1'].geometry}
          />
          <mesh
            name="W-WINDOW-10.6x2.4x0.25m.001_2"
            material={materials['BackColor.017']}
            geometry={nodes['W-WINDOW-10.6x2.4x0.25m.001_2'].geometry}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Skylark/W-WINDOW-06x24x025m.glb')
