/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    ['W_E-BLK_1']: THREE.Mesh
    ['W_E-BLK_2']: THREE.Mesh
  }
  materials: {
    ['FrontColor.010']: THREE.MeshStandardMaterial
    ['BackColor.018']: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/Skylark/W_E-BLK.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="W_E-BLK" rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'W_E-BLK' }}>
          <mesh name="W_E-BLK_1" material={materials['FrontColor.010']} geometry={nodes['W_E-BLK_1'].geometry} />
          <mesh name="W_E-BLK_2" material={materials['BackColor.018']} geometry={nodes['W_E-BLK_2'].geometry} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Skylark/W_E-BLK.glb')
