/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    ['S-WINDOW-2.4x2.4x0.25m_1']: THREE.Mesh
    ['S-WINDOW-2.4x2.4x0.25m_2']: THREE.Mesh
  }
  materials: {
    ['FrontColor.006']: THREE.MeshStandardMaterial
    ['BackColor.012']: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/Skylark/S-WINDOW-24x24x025m.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="S-WINDOW-24x24x025m" rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'S-WINDOW-2.4x2.4x0.25m' }}>
          <mesh
            name="S-WINDOW-2.4x2.4x0.25m_1"
            material={materials['FrontColor.006']}
            geometry={nodes['S-WINDOW-2.4x2.4x0.25m_1'].geometry}
          />
          <mesh
            name="S-WINDOW-2.4x2.4x0.25m_2"
            material={materials['BackColor.012']}
            geometry={nodes['S-WINDOW-2.4x2.4x0.25m_2'].geometry}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Skylark/S-WINDOW-24x24x025m.glb')
