/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    ['N_S BLK_1']: THREE.Mesh
    ['N_S BLK_2']: THREE.Mesh
  }
  materials: {
    ['FrontColor.004']: THREE.MeshStandardMaterial
    ['BackColor.008']: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/Skylark/N_S-BLOCK.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="N_S_BLK" rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'N_S BLK' }}>
          <mesh name="N_S BLK_1" material={materials['FrontColor.004']} geometry={nodes['N_S BLK_1'].geometry} />
          <mesh name="N_S BLK_2" material={materials['BackColor.008']} geometry={nodes['N_S BLK_2'].geometry} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Skylark/N_S-BLOCK.glb')
