/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    ['E-DOOR-1.2x3x0.25m.001_1']: THREE.Mesh
    ['E-DOOR-1.2x3x0.25m.001_2']: THREE.Mesh
  }
  materials: {
    ['_auto_.003']: THREE.MeshStandardMaterial
    ['M_0010_Snow.003']: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/Skylark/E-DOOR-12x3x025m.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="E-DOOR-12x3x025m001" rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'E-DOOR-1.2x3x0.25m.001' }}>
          <mesh
            name="E-DOOR-1.2x3x0.25m.001_1"
            material={materials['_auto_.003']}
            geometry={nodes['E-DOOR-1.2x3x0.25m.001_1'].geometry}
          />
          <mesh
            name="E-DOOR-1.2x3x0.25m.001_2"
            material={materials['M_0010_Snow.003']}
            geometry={nodes['E-DOOR-1.2x3x0.25m.001_2'].geometry}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Skylark/E-DOOR-12x3x025m.glb')
