/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'
import { useHover } from '../modelUtils'; 

type GLTFResult = GLTF & {
  nodes: {
    ['B-1_1']: THREE.Mesh
    ['B-1_2']: THREE.Mesh
  }
  materials: {
    ['diffuse_0_0_0_255.006']: THREE.MeshStandardMaterial
    ['Wood-3 Ver.006']: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/Swift/B1.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="B-1" rotation={[Math.PI / 2, 0, 0]}>
          <mesh  {...useHover() } name="B-1_1" material={materials['diffuse_0_0_0_255.006']} geometry={nodes['B-1_1'].geometry} />
          <mesh  {...useHover() } name="B-1_2" material={materials['Wood-3 Ver.006']} geometry={nodes['B-1_2'].geometry} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Swift/B1.glb')
