/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'
import { useHover } from '../modelUtils'; 

type GLTFResult = GLTF & {
  nodes: {
    ['C-5_1']: THREE.Mesh
    ['C-5_2']: THREE.Mesh
  }
  materials: {
    ['Wood-3 Ver.017']: THREE.MeshStandardMaterial
    ['diffuse_0_0_0_255.017']: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/Swift/C5.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="C-5" rotation={[Math.PI / 2, 0, 0]}>
          <mesh  {...useHover() } name="C-5_1" material={materials['Wood-3 Ver.017']} geometry={nodes['C-5_1'].geometry} />
          <mesh  {...useHover() } name="C-5_2" material={materials['diffuse_0_0_0_255.017']} geometry={nodes['C-5_2'].geometry} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Swift/C5.glb')
