/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    EndLongBlock_1: THREE.Mesh
    EndLongBlock_2: THREE.Mesh
  }
  materials: {
    FrontColor: THREE.MeshStandardMaterial
    BackColor: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/Skylark/EndLongBlock.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="EndLongBlock" rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'EndLongBlock' }}>
          <mesh name="EndLongBlock_1" material={materials.FrontColor} geometry={nodes.EndLongBlock_1.geometry} />
          <mesh name="EndLongBlock_2" material={materials.BackColor} geometry={nodes.EndLongBlock_2.geometry} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Skylark/EndLongBlock.glb')
