/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    MiddleUnderBlockx4_1: THREE.Mesh
    MiddleUnderBlockx4_2: THREE.Mesh
  }
  materials: {
    ['FrontColor.004']: THREE.MeshStandardMaterial
    ['BackColor.004']: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/Skylark/MiddleUnderBlockx4.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="MiddleUnderBlockx4" rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'MiddleUnderBlockx4' }}>
          <mesh
            name="MiddleUnderBlockx4_1"
            material={materials['FrontColor.004']}
            geometry={nodes.MiddleUnderBlockx4_1.geometry}
          />
          <mesh
            name="MiddleUnderBlockx4_2"
            material={materials['BackColor.004']}
            geometry={nodes.MiddleUnderBlockx4_2.geometry}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Skylark/MiddleUnderBlockx4.glb')
