/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    MiddeUnderBlock_1: THREE.Mesh
    MiddeUnderBlock_2: THREE.Mesh
  }
  materials: {
    ['FrontColor.002']: THREE.MeshStandardMaterial
    ['BackColor.002']: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/Skylark/MiddleUnderBlock.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="MiddeUnderBlock" rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'MiddeUnderBlock' }}>
          <mesh
            name="MiddeUnderBlock_1"
            material={materials['FrontColor.002']}
            geometry={nodes.MiddeUnderBlock_1.geometry}
          />
          <mesh
            name="MiddeUnderBlock_2"
            material={materials['BackColor.002']}
            geometry={nodes.MiddeUnderBlock_2.geometry}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Skylark/MiddleUnderBlock.glb')
