/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    RoofRtoL_1: THREE.Mesh
    RoofRtoL_2: THREE.Mesh
  }
  materials: {
    ['FrontColor.005']: THREE.MeshStandardMaterial
    ['BackColor.005']: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/Skylark/RoofRtoL.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="RoofRtoL" rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'RoofRtoL' }}>
          <mesh name="RoofRtoL_1" material={materials['FrontColor.005']} geometry={nodes.RoofRtoL_1.geometry} />
          <mesh name="RoofRtoL_2" material={materials['BackColor.005']} geometry={nodes.RoofRtoL_2.geometry} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Skylark/RoofRtoL.glb')
