/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    SideUnderBlock_1: THREE.Mesh
    SideUnderBlock_2: THREE.Mesh
  }
  materials: {
    ['FrontColor.006']: THREE.MeshStandardMaterial
    ['BackColor.006']: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/Skylark/SideUnderBlock.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="SideUnderBlock" rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'SideUnderBlock' }}>
          <mesh
            name="SideUnderBlock_1"
            material={materials['FrontColor.006']}
            geometry={nodes.SideUnderBlock_1.geometry}
          />
          <mesh
            name="SideUnderBlock_2"
            material={materials['BackColor.006']}
            geometry={nodes.SideUnderBlock_2.geometry}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Skylark/SideUnderBlock.glb')
