/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    ['Wall-Fill_1']: THREE.Mesh
    ['Wall-Fill_2']: THREE.Mesh
  }
  materials: {
    ['FrontColor.007']: THREE.MeshStandardMaterial
    ['BackColor.007']: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/Skylark/WallFill.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Wall-Fill" rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'Wall-Fill' }}>
          <mesh name="Wall-Fill_1" material={materials['FrontColor.007']} geometry={nodes['Wall-Fill_1'].geometry} />
          <mesh name="Wall-Fill_2" material={materials['BackColor.007']} geometry={nodes['Wall-Fill_2'].geometry} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Skylark/WallFill.glb')
