/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    ['Window-2_1']: THREE.Mesh
    ['Window-2_2']: THREE.Mesh
  }
  materials: {
    ['FrontColor.009']: THREE.MeshStandardMaterial
    ['BackColor.009']: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/Skylark/Window-2.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Window-2" rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'Window-2' }}>
          <mesh name="Window-2_1" material={materials['FrontColor.009']} geometry={nodes['Window-2_1'].geometry} />
          <mesh name="Window-2_2" material={materials['BackColor.009']} geometry={nodes['Window-2_2'].geometry} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Skylark/Window-2.glb')
