/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    ['Window-4_1']: THREE.Mesh
    ['Window-4_2']: THREE.Mesh
  }
  materials: {
    ['FrontColor.010']: THREE.MeshStandardMaterial
    ['BackColor.010']: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/Skylark/Window-4.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Window-4" rotation={[Math.PI / 2, 0, 0]} userData={{ name: 'Window-4' }}>
          <mesh name="Window-4_1" material={materials['FrontColor.010']} geometry={nodes['Window-4_1'].geometry} />
          <mesh name="Window-4_2" material={materials['BackColor.010']} geometry={nodes['Window-4_2'].geometry} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Skylark/Window-4.glb')
