/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'
import { Html } from '@react-three/drei';

import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

import { plywoodMaterial } from '../../materials/plywoodMaterial'; 
import { zincMaterial  } from '../../materials/zincMaterial'; 

type GLTFResult = GLTF & {
  nodes: {
    untitled_1: THREE.Mesh
    untitled_2: THREE.Mesh
    untitled_3: THREE.Mesh
    untitled_4: THREE.Mesh
    untitled_5: THREE.Mesh
    untitled_6: THREE.Mesh
    untitled_7: THREE.Mesh
    untitled_8: THREE.Mesh
    untitled_9: THREE.Mesh
    untitled_10: THREE.Mesh
    untitled_11: THREE.Mesh
    untitled_12: THREE.Mesh
    untitled_13: THREE.Mesh
    untitled_14: THREE.Mesh
    untitled_15: THREE.Mesh
    untitled_16: THREE.Mesh
    untitled_17: THREE.Mesh
    untitled_18: THREE.Mesh
    untitled_19: THREE.Mesh
    untitled_20: THREE.Mesh
    untitled_21: THREE.Mesh
    untitled_22: THREE.Mesh
  }
  materials: {
    Timber: THREE.MeshStandardMaterial
    BackColor: THREE.MeshStandardMaterial
    FrontColor: THREE.MeshStandardMaterial
    Translucent_Glass_Gray: THREE.MeshStandardMaterial
    Color_M00: THREE.MeshStandardMaterial
    _White_: THREE.MeshStandardMaterial
    Wood_Plywood_Knots: THREE.MeshStandardMaterial
    Color_001: THREE.MeshStandardMaterial
    Inox_Chiuveta: THREE.MeshStandardMaterial
    _9: THREE.MeshStandardMaterial
    balic_berch1: THREE.MeshStandardMaterial
    Color_D09: THREE.MeshStandardMaterial
    _11: THREE.MeshStandardMaterial
    _LightGray_: THREE.MeshStandardMaterial
    _DimGray_: THREE.MeshStandardMaterial
    M_0010_Snow: THREE.MeshStandardMaterial
    _Translucent_Glass_Gray_1: THREE.MeshStandardMaterial
    _2: THREE.MeshStandardMaterial
    M_96_96_1: THREE.MeshStandardMaterial
    prettyplastic: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/skylark_gltf_skylark.glb') as GLTFResult

  const state = {
    showHTML: false
  }

  return (
    <group 
      ref={group} 
      {...props} 
      dispose={null}
      castShadow={true}
      receiveShadow={true}
      onClick={
        (e) => {
          e.stopPropagation()
          state.showHTML = !state.showHTML; 
        }
      }
      
    >
      <group rotation={[Math.PI / 2, 0, 0]}>
        {state.showHTML == true  ? <Html> <a>  Skylark House </a></Html> : <Html> <a>  </a></Html>}
        <mesh material={plywoodMaterial} geometry={nodes.untitled_1.geometry} />
        <mesh material={plywoodMaterial} geometry={nodes.untitled_2.geometry} />
        <mesh material={plywoodMaterial} geometry={nodes.untitled_3.geometry} />
        <mesh material={materials.Translucent_Glass_Gray} geometry={nodes.untitled_4.geometry} />
        <mesh material={plywoodMaterial} geometry={nodes.untitled_5.geometry} />
        <mesh material={plywoodMaterial} geometry={nodes.untitled_6.geometry} />
        <mesh material={plywoodMaterial} geometry={nodes.untitled_7.geometry} />
        <mesh material={plywoodMaterial} geometry={nodes.untitled_8.geometry} />
        <mesh material={plywoodMaterial} geometry={nodes.untitled_9.geometry} />
        <mesh material={plywoodMaterial} geometry={nodes.untitled_10.geometry} />
        <mesh material={plywoodMaterial} geometry={nodes.untitled_11.geometry} />
        <mesh material={plywoodMaterial} geometry={nodes.untitled_12.geometry} />
        <mesh material={plywoodMaterial} geometry={nodes.untitled_13.geometry} />
        <mesh material={plywoodMaterial} geometry={nodes.untitled_14.geometry} />
        <mesh material={plywoodMaterial} geometry={nodes.untitled_15.geometry} />
        <mesh material={zincMaterial} geometry={nodes.untitled_16.geometry} />
        <mesh material={zincMaterial} geometry={nodes.untitled_17.geometry} />
        <mesh material={zincMaterial} geometry={nodes.untitled_18.geometry} />
        <mesh material={materials._Translucent_Glass_Gray_1} geometry={nodes.untitled_19.geometry} />
        <mesh material={zincMaterial} geometry={nodes.untitled_20.geometry} />
        <mesh material={zincMaterial} geometry={nodes.untitled_21.geometry} />
        {/* <mesh material={zincMaterial} geometry={nodes.untitled_22.geometry} /> */}
      </group>
    </group>
  )
}

useGLTF.preload('/skylark_gltf_skylark.glb')
